# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        # User defined upload name. Visible in Codecov UI
        name: coverage
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: 3d969b92-8b5f-4f31-a670-d9f530c9187d
        # Path to coverage file to upload
        file: ./example.xml
